
###
GET {{mathew_api_HostAddress}}/incomesource?familyId=1
Accept: application/json
Content-Type: application/json

###
GET {{mathew_api_HostAddress}}/incomesource/4?familyId=1
Accept: application/json
Content-Type: application/json


### new

POST {{mathew_api_HostAddress}}/incomesource?familyId=1
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "name": "string",
  "description": "string",
  "projectedIncome": 7500
}

### update
POST {{mathew_api_HostAddress}}/incomesource?familyId=1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "salario",
  "description": "salario",
  "projectedIncome": 0
}
###


DELETE {{mathew_api_HostAddress}}/incomesource?familyId=1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "salario",
  "description": "salario",
  "projectedIncome": 0
}
###
