### Mathew API - General Endpoints
### This file contains general API information and common endpoints
### For specific resources, see their dedicated .http files:
### - category.http
### - expenses.http
### - budget.http
### - income.http
### - income-source.http
### - reimbursement.http
### - user.http
### - family.http
### - report.http

### Health Check
GET {{mathew_api_HostAddress}}/
Accept: application/json
