
###
GET {{mathew_api_HostAddress}}/budget/2025/10
Accept: application/json
Content-Type: application/json


### new

POST {{mathew_api_HostAddress}}/budget
Accept: application/json
Content-Type: application/json

{
  "categoryId": 0,
  "amount": 15.5,
  "month": 12,
  "year": 2025,
  "category": {
    "id": 4,
    "name": "string",
    "description": "string",
    "icon": "string",
    "color": "string"
  }
}

### update
POST {{mathew_api_HostAddress}}/budget
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "categoryId": 4,
  "amount": 15.50,
  "month": 12,
  "year": 2025,
  "category": {
    "id": 4,
    "name": "gatos",
    "description": "comida, insumos, veterinario, paseos\n",
    "icon": null,
    "color": null
  }
}
###


DELETE {{mathew_api_HostAddress}}/budget
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "categoryId": 4,
  "amount": 15.50,
  "month": 12,
  "year": 2025,
  "category": {
    "id": 4,
    "name": "gatos",
    "description": "comida, insumos, veterinario, paseos\n",
    "icon": null,
    "color": null
  }
}
###
