
###
GET {{mathew_api_HostAddress}}/incomesource
Accept: application/json
Content-Type: application/json

###
GET {{mathew_api_HostAddress}}/incomesource/4
Accept: application/json
Content-Type: application/json


### new

POST {{mathew_api_HostAddress}}/incomesource
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "name": "string",
  "description": "string",
  "projectedincome":7500
}

### update
POST {{mathew_api_HostAddress}}/incomesource
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "salario",
  "description": "salario"
}
###


DELETE {{mathew_api_HostAddress}}/incomesource
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "salario",
  "description": "salario"
}
###
